### ISSUE TITLE
Accept custom scroll states on route change

### ISSUE THREAD

**Issue by mishkinf** [TrueCar/gluestick#1012]
Currently, we are using react-router-scroll in order to support setting the scroll state of the window upon route change. Accept a custom callback to control the scroll state upon window navigation. This will allow us to support things like hash anchor links to deep link to content on a particular page  and leveraging query string params to filter content on the page without having the page pop to the top. 

In Root.js the code might be akin to...

```javascript
const render: Function = applyRouterMiddleware(
  useScroll((prevRouterProps, { location, routes }) => {
    routes.forEach((route) => {
      if (route.useScroll) {
        return route.useScroll(prevRouterProps, location);
      }
    });

    if (routes.some(route => route.ignoreScrollBehavior)) {
      return false;
    }
    return true;
  }),
);
```

and then a client application could define a custom handler for scrolling on each route like so... 

```javascript
// routes definitions
<Route useScroll={customScrollBehavior} path="some_path" component={SomeComponent} />
// end routes definitions

const customScrollBehavior = (prevRouterProps, location) => {
  // first check for hash anchors and if so.. let the browser handle it as normal 
  if (location.hash) { return true; }

  // if the page changes scroll to top of page on path change
  if (prevRouterProps && location.pathname !== prevRouterProps.location.pathname) {
    return [0, 0];
  }

  // default browser scroll behavior
  return true;
};
```

**Comment by zamotany** [comment]
Can you provide some example with `useScroll` prop so it'll be easier to test it?
