### ISSUE TITLE
flaw in scripts/build.js if local gluestick is in folder named `src`

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#1025]
In the file [scripts/build.js#32](https://github.com/TrueCar/gluestick/blob/next/scripts/build.js#L32) there is some code that will replace `src` with `build`. We were running this on a machine where `gluestick` was cloned into a folder _~/src/gluestick_. This resulted in the build folder being placed directly in the home folder _~/build_ instead of _~/src/gluestick/packages/build_ as it is intended.

The simple fix is likely to replace the *last* occurrence or `src` or simply resolve the path relative to the dirname. I would favor a relative path based on __dirname as that is likely the most reliable way to resolve this issue.

**Comment by threehams** [comment]
Please go the second route. Replacing anything in an absolute path is exceedingly dangerous - imagine if this were `rm -rf` instead of a copy operation.
