### ISSUE TITLE
Issues with static build option re: S3 hosting

### ISSUE THREAD

**Issue by marcdel** [TrueCar/gluestick#1030]
Hey, so build --static is no longer printing an exception, but I'm still not entirely sure how to use this option. Is there a flag or env variable I can pass to specify a relative path to the assets in the generated html file? The `ASSET_URL` environment variable doesn't seem to have any affect.

My use case is deploying a static build to S3 hosting. I need to be able to reference the assets as `../assets/whatever.js` rather than `http://0.0.0.0:8888/assets/whatever.js` as it's currently doing.

The S3 hosting is currently set up to look for an index.html at the root, but I can modify the Jenkins job to move build/static/main.html to build/index.html before I push the files up to S3, but obviously that doesn't work if the asset references are still `../assets/main.js` or something.

Wondering if you folks have any suggestions for getting around that.

Thanks!

**Comment by zamotany** [comment]
I've digged more into it, and I found few bugs:
- it doesn't work in production
- there is no option to overwrite asset path

With #1031 it will be available to specify custom asset path via `src/config/application.js` - by default it will try to use `process.env.ASSET_URL`. This will also require `gluestick-env-expose-ast` plugin to be enabled.
