### ISSUE TITLE
runBeforeRoutes and trailing slash problems

### ISSUE THREAD

**Issue by lukewalczak** [TrueCar/gluestick#1043]
In internal project everytime when we navigate to a different page with an url that has no trailing slash, we have an error message `Cannot read property 'params' of undefined` in `gluestick/shared/lib/route-helper.js`. We force trailing slashes in our app using `react router v3` and this approach: https://github.com/ReactTraining/react-router/issues/820#issuecomment-256814655

When the url has no slash, it hits `createTransitionHook` two times, first one with undefined `routeParams` so it crashes when trying to access `params`. Second one works ok.

CC @toddw @zamotany

**Comment by zamotany** [comment]
It's not a gluestick bug. In internal project routes were too deeply nested in three `Route` components.
