### ISSUE TITLE
Warning: React attempted to reuse markup...

### ISSUE THREAD

**Issue by kitze** [TrueCar/gluestick#12]
I'm following the tutorial. I've added Todos container and added it to the routes in the config. 

Then i navigated to localhost:8888/todos and i got this error https://i.imgur.com/rc3m4k5.png

I've tried to remove everything related to redux from the component but the error persists.

I've tested this with node 4._, node 5._, Chrome Canary, and normal version of Chrome. Also i've tried it in incognito window without any extensions but the error is still there.

**Comment by toddw** [comment]
I will work on resolving this. The resuse markup error is a bummer and I'm going to fix that but that one specifically shouldn't be causing a crash. The [Resolve] error looks more serious. I'll work on a fix for both

**Comment by kitze** [comment]
@toddw the [Resolve] error is coming from the redux dev tools extension. I don't get it in incognito mode without the extension.

**Comment by toddw** [comment]
Fixed with https://github.com/TrueCar/gluestick/pull/14
