### ISSUE TITLE
Version update script

### ISSUE THREAD

**Issue by christinebrass** [TrueCar/gluestick#140]
Create a version update script that:

1) Updates our npm package version
2) Updates the version in our Dockerfile: https://github.com/TrueCar/gluestick/blob/develop/templates/new/src/config/.Dockerfile. This is already taken care of by the `npm run prepublish` script, but when releasing via GitHub this doesn't get committed in time.

**Comment by michalchudziak** [comment]
About the second part of this task - I'm not really familiar with GitHub releases. Can you tell us a bit more about how are you handling releases in this project? Do we have some hook where we can attach it (just like `npm run prepublish`) or should we think about some different ways of solving this issue?

**Comment by toddw** [comment]
I can fill in some context as to what we do with GitHub releases but I'm going to need to rely on @cybrass to fill in the details for this specific issue:

We have a hook in Travis CI that publishes GlueStick to npm and our docker image to https://hub.docker.com/ when you create a new release. (https://travis-ci.org/TrueCar/gluestick)

Releases can be seen here: https://github.com/TrueCar/gluestick/releases

**Comment by christinebrass** [comment]
Yeah, the way we have it setup now would work best if we were running `npm publish` locally. If we were, this would be our process:

1. Update the version in package.json 
2. Run `npm publish`. This would invoke our prepublish and postpublish scripts for prepping and uploading our GlueStick Docker image
3. Commit the changed .Dockerfile file
4. Tag the set of files and push the tag to GitHub

Releasing with GitHub releases is a little different, in that it tags the set of files for you when you "publish" the release. Here's the process we currently follow with GitHub releases:

1. Update the version in both the package.json file and the .Dockerfile file
2. Commit and push those changes to GitHub
3. Use the GitHub Releases section to draft and publish a new release. This is where we enter the git tag we want to use for the release

From there, our [Travis CI hook](https://github.com/TrueCar/gluestick/blob/develop/.travis.yml#L37-L44) does the `npm publish` step, which invokes the same prepublish and postpublish scripts for prepping and uploading the GlueStick Docker image to https://hub.docker.com/r/truecar/gluestick

I originally created this issue to solve Step 1 of this latter process, since in the beginning we were accidentally forgetting to change the version change to the .Dockerfile file after changing the version in package.json. I was thinking it would be nice to run a single script to update both the package.json file and the .Dockerfile at the same time. It's sorta trivial, but for someone new to the project it would be less of a hassle to remember to update both files. I'm totally open to suggestions to make the process better if you have any.

**Comment by toddw** [comment]
@cybrass So maybe a script like 'npm run update-version' that will display a prompt which shows you the current version and asks what version you would like to update to. Then it will update package.json and run pre-publish to update the Dockerfile so it matches the view version that was saved in package.json. How does that sound?

**Comment by lukewalczak** [comment]
Just to be sure it should look like :
1. npm command is run locally which updates `package.json` and `template/new/src/config/.Dockerfile`,
2. Those changes are commited to GitHub repo,
3. Release is created on GitHub,
4. Travis CI hook generates `truecar/gluestick` image with updated version and pushes it to the Docker Hub.

Is it correct?

**Comment by toddw** [comment]
That is the flow but most of those steps are already working as they should.
1. The script will prompt the user for which version they would like to update to, once entered it will update package.json. Then it will run [generate-dockerfilejs](https://github.com/TrueCar/gluestick/blob/develop/docker/generate-dockerfile.js) which already exists.

Steps 2-4 are either manual steps and not part of this script, or they are already set up (like step 4 is already set up).

**Comment by christinebrass** [comment]
Yup @toddw and @lukewalczak you guys have the idea. I noticed https://github.com/callstack-io/gluestick/pull/5/files and that's exactly what I had in mind-- and simple too! I like it 😄
