### ISSUE TITLE
Multiple Entry Points

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#141]
It would be nice if GlueStick supported Multiple Entry Points so that you could split a large app into chunks. https://webpack.github.io/docs/multiple-entry-points.html

Currently code splitting is supported by using `require.ensure` but maybe it makes sense to also support multiple entry points.

Right now, all of the reducers are exported as one object in the `reducers/index.js` file but if you have a really large app it might make sense to separate reducers into different places.

I don't have a solution ironed out for this yet but it's something we might need to figure out soon.

**Comment by christinebrass** [comment]
Resolved by #196
