### ISSUE TITLE
Mocha tests re-run after coverage report is generated.

### ISSUE THREAD

**Issue by threehams** [TrueCar/gluestick#160]
Running tests in watch mode (the default) runs a second process which generates a coverage report in the background. Unfortunately, once it finishes, the watcher picks up the changes to the .js files in coverage/ and re-runs the tests. It doesn't cost much in time, but it's a lot of unnecessary and confusing console output.

Mocha's watch is not configurable, and will eventually be deprecated. However, when running Mocha in a spawned process, it is _by far_ the quickest way to re-run tests in a transpiled project.

One possible fix is to have an intermediate script which requires the mochaTestHelper.js file, watches only certain directories, and runs Mocha programatically - which should retain the speed. This is more complicated, and will require rewriting some things we currently get from Mocha for free. However, it may  simplify some of the test.js command code.

**Comment by toddw** [comment]
Closing this in favor of: https://github.com/TrueCar/gluestick/issues/406
