### ISSUE TITLE
Consider using universal-webpack 

### ISSUE THREAD

**Issue by christinebrass** [TrueCar/gluestick#183]
The [universal-webpack](https://github.com/halt-hammerzeit/universal-webpack) project was created as a replacement to [webpack-isomorphic-tools](https://github.com/halt-hammerzeit/webpack-isomorphic-tools). Investigate and possibly replace the old with the new.

**Comment by threehams** [comment]
webpack 2, once released, eliminates the need for anything additional. It may be worth waiting for that.

Found a good example project here, with a great level of documentation on the approach: https://github.com/ctrlplusb/react-universally

**Comment by toddw** [comment]
we considered it and decided it is not the direction we want to go right now but maybe in the future
