### ISSUE TITLE
Consider ignoring certain files from coverage report

### ISSUE THREAD

**Issue by jamesoh** [TrueCar/gluestick#197]
I was wondering what people thought about ignoring files such as `/reducers/index.js`, `/components/react-bootstrap-subset.js`, `/components/react-router-subset.js` and any other files that we won't be writing tests for.

**Comment by toddw** [comment]
@jamesoh Thanks for the suggestion. Out of the three files mentioned only 1 of them is created by gluestick and the others look like app specific files. I'm not sure it would be a good idea to exclude any files from the coverage report. Going to close this for now… please feel free to re-open if you feel strongly about this and have an idea for what that api would look like.
