### ISSUE TITLE
Importing node modules with or without browserify?

### ISSUE THREAD

**Issue by jeveloper** [TrueCar/gluestick#227]
Hi

Curious if there is a good way of integrating browserify to "import from node modules" or perhaps a different way of doing so in gluestick environment.

thanks

**Comment by toddw** [comment]
Hi @jeveloper,
Unfortunately, we do not currently support "node specific" modules at this time. However, there are many modules that are universal/isomorphic that work both on front-end and the backend like `axios`.

What module(s) are you trying to work with? Maybe we can figure out a way to make it work for you or we can talk about what would be required to do what you are trying to do.

**Comment by jeveloper** [comment]
Thanks for your message Todd, i went on to build out a small api that's on node :)
I like gluestick though
