### ISSUE TITLE
Developer Tools Debugger and Warning location is mangled

### ISSUE THREAD

**Issue by jer-k** [TrueCar/gluestick#274]
When I place a debugger in my code and it is reached, the Developer Tools end up on this file, instead of the location of the debugger.
![image](https://cloud.githubusercontent.com/assets/1280586/18145604/d114812a-6f80-11e6-88b5-8219708510ef.png)

The same goes for warning that are output. 
![image](https://cloud.githubusercontent.com/assets/1280586/18145508/704cee0e-6f80-11e6-99d0-7d94def32fa4.png)

Multiple developers have seen this so I don't believe it is an issue related specifically to my machine or project.

**Comment by toddw** [comment]
This was fixed by switching the devtool type https://github.com/TrueCar/gluestick/pull/284
