### ISSUE TITLE
css files imported in Index.js don't seem to be included in the production bundle

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#276]
Most likely this broke with the multiple entry points stuff that was added. In a sample app I spun up I couldn't reproduce but in a couple of existing apps I am able to reproduce. I'll work more details when I get more time.

**Comment by saltycrane** [comment]
For me, the existence of an entry in `entryPoints` in the `webpack-additions.js` file affected whether the CSS file was generated. With `entryPoints` empty I got a `main.css` but with something in `entryPoints`, I didn't get `main.css` and I got `vendor.css`.

**Comment by toddw** [comment]
thanks @saltycrane … that is the missing piece of information that I hadn't had time to track down yet. It should be relatively easy to resolve now that we know that.

**Comment by zamotany** [comment]
Closed issue as PR is merged.
