### ISSUE TITLE
additionalLoaders doesn't support overriding loader built into Gluestick

### ISSUE THREAD

**Issue by threehams** [TrueCar/gluestick#304]
The interface for adding additional loaders (app configuration) only allows for adding loaders for extensions, not modifying existing loader configuration. For css/scss/sass, an override mechanism would be needed to support CSS modules, a prerequisite for getting Gluestick working with react-toolbox.

**Comment by toddw** [comment]
Closing in favor of https://github.com/TrueCar/gluestick/issues/407
