### ISSUE TITLE
Expose Webpack config for changes prior to build

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#407]
Currently GlueStick has almost 100% control of the webpack config. The only exception to this are the hooks we have added via `src/config/webpack-additions.js`. Instead of providing individual hooks for specific parts of the webpack config that we allow to be extended, it would be better to provide 1 hook where a user gets the webpack config and can return a modified version that will be used by GlueStick. This way they can intercept things like our css loaders and remove/modify/add any loaders they want, they can change the `devtool` setting, or anything that exists in that object.

This would likely eliminate the need for `src/config/webpack-additions.js` or at least how it stands in it's current form.

**Comment by michalchudziak** [comment]
Now there are few hooks exposed to user:

```js
{
  additionalAliases,
  additionalExternals,
  additionalLoaders,
  additionalPreLoaders,
  additionalWebpackNodeConfig,
  vendor,
  plugins,
  entryPoints
}
```
 
I was playing around with `webpack-merge` library and replaced all those hooks with single `webpack-config` file in generated application, but I felt like something is missing there (especially entrypoints hook).

Should we keep some hooks and add a new one for whole config file? I would keep `entryPoints` hook, and maybe `vendor` one as well, so hook structure would look like this:

```js
{
  config,
  vendor,
  entryPoints
}
```

What do you think - should we go for single `config` file, or keep those hooks?

**Comment by toddw** [comment]
resolved by https://github.com/TrueCar/gluestick/pull/433
