### ISSUE TITLE
Allow httpClient to be accessed within onEnter hooks

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#410]
Currently, `httpClient` is only accessible via the promiseMiddleware. In an action creator, if you pass a function to the `promise` key it will get the `httpClient` passed to it. The advantage of using this instead of plain axios, is that this will be the configured axios client. That way if you pass a value to `httpTransforms` in src/config/application.js those will be applied to the httpClient. Also, on server side requests, relative URLs will be automatically converted to full URLs so that they will work in server side requests. Additionally, on server side requests, cookies are also grouped together for you via https://github.com/TrueCar/gluestick-shared/blob/master/src/lib/getHttpClient.js

Really we want to be able to pass the result of `getHttpClient` to an `onEnter` hook but in order to do so we need to be able to pass along `options={}, req, res,`. `req`, and `res` are references to express request and response objects generated by a server side request. They are not required when building an http client in the browser so they are optional arguments but they should be passed when being run on the server.

**Comment by michalchudziak** [comment]
Are you talking about *react-router's* `onEnter` hook in generated project or anything else? Would be nice if we could clarify this one :)

**Comment by toddw** [comment]
Yeah sorry that is exactly what I'm talking about. _react-router's_ `onEnter` hook.

**Comment by toddw** [comment]
resolved by https://github.com/TrueCar/gluestick/pull/455
