### ISSUE TITLE
Change how we add redux middleware to increase customizability

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#412]
Currently we expose an array in _src/config/redux-middleware.js_ but that doesn't give enough control for use cases where you want to push middleware to the front or the end of the stack… or even remove our default promise middleware if you want. Instead, we should provide a hook that gets the middleware array, gives developers a chance to modify it and return a new or modified version of it. This will give developers more control

**Comment by grabbou** [comment]
To make it backwards-compat, I suggest to detect if file contains a function as a default export, pass it current array of middlewares and expect a modified stack to be returned. Otherwise, treat as currently.
