### ISSUE TITLE
Refactor the interface of commands

### ISSUE THREAD

**Issue by grabbou** [TrueCar/gluestick#418]
As discussed today, there's what we currently do in React Native.

We have a type (flow) of a command https://github.com/facebook/react-native/blob/master/local-cli/commands.js#L17-L36 and we export an array of them. 

There's a file, cli.js that builds an interface based on that - https://github.com/facebook/react-native/blob/master/local-cli/cliEntry.js#L94

And a sample command is https://github.com/facebook/react-native/blob/master/local-cli/link/link.js#L175-L179

**Comment by toddw** [comment]
added to 1.0 sprint
