### ISSUE TITLE
Declarative generator API and custom generators

### ISSUE THREAD

**Issue by zamotany** [TrueCar/gluestick#419]
I belive it would be great if user could write it own custom generator and then use it with GlueStick CLI (similarly to Aurelia CLI). This would require to make declarative generator API or by configs (like JSON for instance) file. User would then generate generator template, fill it/configure and use it as it would use for example `component` template.

Possible use:
1. Generate generator template
```
gluestick generate generator // or something similar like `gluestick generate --new`
```
2. Configure it
3. Use
```
gluestick generate myCustomWhatever
```

**Comment by toddw** [comment]
Yeah, we talked about this in the past and I agree it would be nice to have. I'll add it to the 1.0 sprint

**Comment by zamotany** [comment]
Merged
