### ISSUE TITLE
Upgrade to webpack v2.2

### ISSUE THREAD

**Issue by michalchudziak** [TrueCar/gluestick#427]
How would you feel about upgrading webpack to the latest version? I think it's final version atm 😎

There is guide on how to migrate from version 1.x
https://webpack.js.org/guides/migrating/

**Comment by toddw** [comment]
At the time of writing this ticket, I believe webpack 2.2 was the latest. I'll update the title to update to latest webpack :)

**Comment by toddw** [comment]
Oh sorry. I assumed we created this ticket and you were asking for clarification. Yes, updating to the latest webpack sounds great :)
