### ISSUE TITLE
Error with gluestick start

### ISSUE THREAD

**Issue by sawan** [TrueCar/gluestick#43]
Hi,

I get the following error on starting up:

``` bash
./node_modules/.bin/gluestick start
watching C:\Cygwn\home\xx\myAppdir

{"0":{"code":"ENOENT","errno":"ENOENT","syscall":"spawn gluestick","path":"gluestick","spawnargs":["start-client"]}}
{"0":{"code":"ENOENT","errno":"ENOENT","syscall":"spawn gluestick","path":"gluestick","spawnargs":["start-server"]}}
{"0":{"code":"ENOENT","errno":"ENOENT","syscall":"spawn gluestick","path":"gluestick","spawnargs":["start-test"]}}
[change detected] restarting server… src\containers\NoMatchApp.js
{"0":{"code":"ENOENT","errno":"ENOENT","syscall":"spawn gluestick","path":"gluestick","spawnargs":["start-server"]}}
```

This is happening on Windows. Does gluestick have to be installed globally? I was able to install locally in a dir and generate the initial app structure, but the start command fails.

**Comment by toddw** [comment]
Thanks for opening this issue. `gluestick` does need to be installed globally. We are not currently targeting Windows support but if you have another pull request that improves support on Windows we will definitely work to get it merged again.
