### ISSUE TITLE
Move gluestick-shared to Gluestick monorepo

### ISSUE THREAD

**Issue by grabbou** [TrueCar/gluestick#438]
Likely not actionable just yet, but a placeholder for setting up `lerna` and monorepo in place.

**Comment by grabbou** [comment]
@toddw we will have a lot of stuff to discuss here

**Comment by christinebrass** [comment]
@grabbou I think it's a great idea, and something we considered in the past as well. I think we just need to think about how this will affect our release process with Travis CI, etc. Right now we have https://github.com/TrueCar/gluestick-shared and https://github.com/TrueCar/babel-plugin-gluestick that would be good candidates for merging into the monorepo. I think there was some talk of creating a separate gluestick-cli package as well, so things may get re-arranged depending on the outcome of all that.

**Comment by grabbou** [comment]
Thanks @cybrass for putting additional context into this issue, I will definitely investigate the build process of other packages and come up here with a plan on how it all could work.

**Comment by ferrannp** [comment]
@toddw & @cybrass I plan to merge https://github.com/TrueCar/gluestick-shared and https://github.com/TrueCar/babel-plugin-gluestick here using lerna (`v2`). Is it a good moment? Any pending work on those repos ?

**Comment by toddw** [comment]
@ferrannp We still have 1 last ticket left for GlueStick v1 https://github.com/TrueCar/gluestick/projects/1 which is actually a gluestick-shared ticket https://github.com/TrueCar/gluestick-shared/issues/21

If you don't mind cherry-picking the changes then I'm totally fine with that in the v2 branch

**Comment by ferrannp** [comment]
This is done and merge. I'll keep the branch open to remove unnecessary stuff from `gluestick-shared`.
