### ISSUE TITLE
Update dependencies.

### ISSUE THREAD

**Issue by michalchudziak** [TrueCar/gluestick#444]
We have a lot of dependencies which are out of date:

![image](https://cloud.githubusercontent.com/assets/7837457/22205240/2ec4078e-e176-11e6-925f-6dbffd79a1f2.png)

I know not all of them can be easily upgraded, but maybe we can think about getting at least some of them up to date.

**Comment by grabbou** [comment]
+1 here, but work has to be done to ensure the major bump does not affect the codebase. Also, let's keep in mind people often do not know how to use `semver` properly.
