### ISSUE TITLE
Setting up Flow and start using it

### ISSUE THREAD

**Issue by ferrannp** [TrueCar/gluestick#446]
For example, this file [getRenderRequirementsFromEntrypoints.js](https://github.com/TrueCar/gluestick/blob/570fb01a806c246fef4b0bf8a09e974c8958a8c5/src/lib/server/getRenderRequirementsFromEntrypoints.js#L37) has no `flow` tag. So we miss things like:

```
const httpClient = getHttpClient(config.httpClient, req, res);
```

And if you check config generated in [application.js](https://github.com/TrueCar/gluestick/blob/f52e1748ab8b4ce3ab0a4365371e20927c554ccd/templates/new/src/config/application.js) template, there is no such field like `config.httpClient`. 

We can avoid this using Flow.

**Comment by grabbou** [comment]
+1 to use `flow` where possible. We could establish a rule that every file we refactor has to be enhanced with `flow`, otherwise ignore?

There's a lot of opportunities here we could utilise in order to make it a seamless upgrade.
