### ISSUE TITLE
Releases via GitHub no longer pushes Docker image to DockerHub

### ISSUE THREAD

**Issue by christinebrass** [TrueCar/gluestick#448]
We have a [`postpublish`](https://github.com/TrueCar/gluestick/blob/develop/package.json#L15) hook that gets run every time we tag & release a new version of GlueStick.   Lately, we've received build issues related to this hook that complains about a missing `cross-spawn` module. I was able to replicate this with certain versions of yarn, so I thought pinning the version would help, but that doesn't seem to be the case.

Since the build fails, Docker images no longer automatically get pushed to our repository at [DockerHub](https://hub.docker.com/r/truecar/gluestick/). Our current workaround for this is to build the image in our own sandboxes and push ourselves.

**Comment by christinebrass** [comment]
Travis CI log with the issue here (search for 'cross-spawn'): https://s3.amazonaws.com/archive.travis-ci.org/jobs/193923002/log.txt

**Comment by zamotany** [comment]
Why use `cross-spawn` at all?? From what I know we ditched support for Windows so I don't think we need that module. Besides Travis run on Linux so there we definitely do not need it. Replacing `cross-spawn` with `child_process` would quickly resolve issue.

**Comment by christinebrass** [comment]
We verified that this was actually resolved by #443, but yes we can remove `cross-spawn` from that script.
