### ISSUE TITLE
Remove Mocha/Karma/node-inspector/instanbul related code

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#452]
Now that we are using Jest it seems like we should remove the dead code paths for previous testing approaches. I think we should remove anything related to Mocha/Karma/node-inspector and instanbul.

**Comment by ferrannp** [comment]
Mmm but isn't this depending on #447 ?

**Comment by toddw** [comment]
Yeah, some of these have been done, and some are blocked but I wanted a ticket to track all of it to make sure it doesn't slip through the cracks.
