### ISSUE TITLE
Migrate to universal-webpack instead of webpack-isomorphic-tools

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#454]
It has been brought up in the past that we should consider universal-webpack as an alternative to using webpack-isomorphic-tools.
https://github.com/halt-hammerzeit/universal-webpack

**Comment by michalchudziak** [comment]
`universal-webpack` docs claim that:

> This library now only supports Webpack 2.

I think we need to wait for https://github.com/TrueCar/gluestick/pull/456 to be merged, and then start working on this one 😎
