### ISSUE TITLE
Make a better Home example when generating a new project

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#460]
Currently, when you generate a new gluestick project, start it up and open in the browser you are greeted with:
```
Home
```

I think we should consider making the Home component a little more impressive. One one hand, I'm certain they are going to wipe it away. I don't want to create a lot of work for someone to _remove_ stuff we did just to make the project excite new users. On the other hand, it is very anticlimactic when you open your browser to http://localhost:8888/

This is what I propose:
We create an exciting/interesting component outside of the Home component like:
_src/components/WelcomeToGlueStick.js_

Then in the demo home project, instead of `<div>Home</div>` we have `<div><WelcomeToGlueStick /></div>`

This way, it is just as easy to remove the welcome message as it is to remove `Home`. Well, almost, they may want to delete the component too but I think it would be worth it.

As far as what WelcomeToGlueStick should have… I think it should be a decently designed page that explains a number of the features you get with GlueStick. Almost like a super abbreviated version of a GettingStarted guide.

What does everyone think?

**Comment by toddw** [comment]
This probably goes without saying but we don't want to have to include any third party modules for building _WelcomeToGluestick_. We don't want to add things to the dependency tree just for the welcome message.

**Comment by michalchudziak** [comment]
Yeah - how would you feel about `Welcome to GlueStick!` header with some basic usage info and simple styles?

Do you have anything on your mind which you want to be present on welcome page?

**Comment by michalchudziak** [comment]
I think we could list some basic commands with explanation like: 
- `gluestick start` + description
- `gluestick test` + description
- etc...

**Comment by toddw** [comment]
I love what Rails has but I think we can do better with some helpful basic commands.
![image](https://cloud.githubusercontent.com/assets/140000/22317451/9272a69c-e328-11e6-97c3-a62eb329880b.png)

I might be able to get our designers to do something for us

**Comment by toddw** [comment]
I just talked to one of our designers Robby. He is going to put something together 😁 🎉

**Comment by michalchudziak** [comment]
Any luck with getting designs 😇?

**Comment by toddw** [comment]
I will ask Robby today. I haven't seen anything yet

**Comment by toddw** [comment]
Maybe we can implement this basic thing I threw together while we wait for a fancy design :)
![gluestick-welcome-screen](https://cloud.githubusercontent.com/assets/140000/22749327/c74df632-ede1-11e6-8cc1-214d2ab36774.png)

**Comment by zamotany** [comment]
What about some interactive guide to how use gluestick as a Home app?

**Comment by toddw** [comment]
> What about some interactive guide to how use gluestick as a Home app?

That would be awesome!
