### ISSUE TITLE
Change test structure for Gluestick project

### ISSUE THREAD

**Issue by michalchudziak** [TrueCar/gluestick#482]
We think that different structure for tests would be amazing - keeping `__tests__` folder in each directory will make it better for huge projects.

This is the approach recommended (and optional) by Jest. You can see this convention used in [React codebase](https://github.com/facebook/react/tree/master/src).

**Comment by ferrannp** [comment]
If all tests then live in `src`, remember to change the following line https://github.com/TrueCar/gluestick/blob/v1/package.json#L129 to:

```
"testPathDirs": ["src"],
```

**Comment by toddw** [comment]
Is there any way for there to be a backwards compatible way of implementing this?

**Comment by toddw** [comment]
Now that Jest is our testing tool, I'm all for sticking to whatever is standard with that tool but it would be nice if it were possible to support tests written in <=v1 apps

**Comment by ferrannp** [comment]
I'll take a look @toddw.

**Comment by ferrannp** [comment]
@toddw I moved backward compatibility conversation for generated app to #521.
