### ISSUE TITLE
Refactor tests that hit the disk (mocking)

### ISSUE THREAD

**Issue by michalchudziak** [TrueCar/gluestick#483]
Unit tests should mock real behaviours like writing to disk or making network calls. Here you can read an example of mocking `fs` in orther to test functions that depend on it: https://facebook.github.io/jest/docs/manual-mocks.html

**Comment by ferrannp** [comment]
Just for the record, `writeTemplate.test.js` seems to do something similar (mocking `fs`). I can probably prepare a `fs` mock that lives in `__mocks__` and is available for any test.

**Comment by ferrannp** [comment]
I'll wait for #477 to be merged.

**Comment by zamotany** [comment]
- [ ] new command
- [ ] destroy command
