### ISSUE TITLE
React Native compatible

### ISSUE THREAD

**Issue by jellyfangs** [TrueCar/gluestick#5]
Pretty plz :)

**Comment by toddw** [comment]
You should be able to use the reducers in a React Native project but building out a RN app using GlueStick is not really on the roadmap for now. React Native already comes with a CLI for bootstrapping. You would be missing generators, a testing environment and some of the redux stuff we automatically hook up. I can definitely see some value but we need to get further along with the web version first.

Sorry but I'm going to be closing this for now. It is just too far away in the roadmap for now. Feel free to fork and create `gluestick-native` ;)
