### ISSUE TITLE
Change test structure for generated app

### ISSUE THREAD

**Issue by ferrannp** [TrueCar/gluestick#521]
@toddw about backward compatibility with <= v1 for generated apps. I see two options:

1. If an old generated app contains tests in `tests`, they will continue to run, but, new generated components/containers/reducers will place tests into `__tests__` (relative to them)
2. Provide the ability to the user to decide where tests should be stored (ruby way vs jest way)

**Comment by toddw** [comment]
I'm happy with option 1
> If an old generated app contains tests in tests, they will continue to run, but, new generated components/containers/reducers will place tests into __tests__ (relative to them)

**Comment by toddw** [comment]
After spending more time thinking about this, I think we should provide a script that will automatically migrate a project using the older folder structure to the new one. What do people think about that?

This way we encourage people to adapt to the new structure by removing the burden of manually moving the files around and updating them.

**Comment by ferrannp** [comment]
@toddw so you suggest that:

1. New generated apps will have the generated tests placed into `src/**/__tests__`
2. For already generated apps, if you generate a new file, it will place tests to also `src/**/__tests__`
3. Give user a command that can run to move tests from `tests` folder to `src/**/__tests__` (it also needs to change the code so all requires match new path). A requirement is that the test name should be the same name as the file that is testing (plus `.test.js`).

**Comment by grabbou** [comment]
I was asked to hack on the point 3, so let's see what I came up with soon :fire:

**Comment by ferrannp** [comment]
After this discussion on changing the structure https://github.com/TrueCar/gluestick/issues/560 where we will have `shared` folder, we can have multiple apps, etc... We agreed that the hassle to move tests it's not worth (and I am not 100% sure it will be possible anymore).

What we can do is:

- News apps will use new test structure
- New `generate` command will move tests to new structure
- Tests in `test` folder will continue to work, user can slowly move to new structure if they want to

I'll move this on ice for now, if you agree @toddw, I'll remove WIP from https://github.com/TrueCar/gluestick/pull/575.

**Comment by toddw** [comment]
@ferrannp okay, that's fine
