### ISSUE TITLE
Fix babel plugin error when installing gluestick with Yarn

### ISSUE THREAD

**Issue by zamotany** [TrueCar/gluestick#528]
When installing gluestick with Yarn and running it the following error is throw:
```
ReferenceError: Unknown plugin "transform-runtime"
```

**Comment by michalchudziak** [comment]
For now, we should be able to create some workaround to fix this issue and focus on solving this one at the end of the sprint.

Are you ok with that @toddw ?

**Comment by toddw** [comment]
That's fine!

**Comment by sethbattin** [comment]
Extra info: another way to get the transform plugins working correctly was to `yarn link` from a gluestick checkout, `yarn link gluestick` in the target app, and then re-`yarn install` in the app.  That would install additional packages, and `gluestick start` would run without issue.

**Comment by ferrannp** [comment]
CC @mike866 might be related to new command?

**Comment by michalchudziak** [comment]
I think it's rather `yarn` problem, but we need to investigate it a bit more.

**Comment by zamotany** [comment]
<img width="667" alt="screen shot 2017-03-09 at 13 55 52" src="https://cloud.githubusercontent.com/assets/17573635/23751164/5f625b48-04d0-11e7-8743-088b481873a5.png">

Looks like yarn started working properly with `1.0.0-rc.7`

**Comment by zamotany** [comment]
Right now, yarn only works in production but not in dev mode (when passing `--dev` flag).

**Comment by toddw** [comment]
@zamotany does that mean it will work on release candidates?

**Comment by zamotany** [comment]
Yes, after we made a fix to gluestick new command, because now if you try `gluestick new <name> --yarn` it will install deps with yarn, then fail when calling `./node_modules/.bin/gluestick new <name> --yarn` because `new` (in gluestick) does not have option `--yarn` so it will fail.
Right now you can try this on already created project: `rm -rf node_modules` and `yarn`.
