### ISSUE TITLE
[v1] support for folders in generator not working

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#530]
When we were working on refactoring generators it seems as though we may have broken the ability to generate something _into_ a folder.

### Example:
`gluestick generate component used/VehicleDetails`

### Expected Result:
This should create the following files:
_src/components/used/VehicleDetails.js_
_test/components/used/VehicleDetails.js_

### Current Result:
```
[GlueStick] ERROR: Invalid name specified
```

Is this functionality supported in a different way?

Here is a comment left on PR when I first noticed this was broken: https://github.com/TrueCar/gluestick/pull/458#issuecomment-274995877

**Comment by zamotany** [comment]
Regex in `src/generator/index.js` doesn't accept `/` and throws error.
To fix it: modify regex in line 13 like so:
```
if (!/^[a-zA-Z0-9\/]+$/.test(entityName)) {
```
I forgot that `/` can also be used.
