### ISSUE TITLE
[v1] error: unknown option `--debug-server` (gluestick start --debug-server)

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#531]
## Bug
It does not currently work as expected. It appears the option is not being passed from `start` to `start-server`.

`gluestick start --help` shows that `--debug-server` should be a valid option.

### Reproduction Steps
1. Run `gluestick start --debug-server` or `gluestick start -D`

### Result
```
error: unknown option `--debug-server`
```

### Expected Result
It should pass the option to start-server and allow for debugging server side rendering. This works as expected when you run `gluestick start-server` alone.

`gluestick start-server --debug-server` does work as expected.

**Comment by zamotany** [comment]
## How to fix guide for the assignee
Remove 
```
let valueIndex = -1;
```
and add 
```
let valueIndex = args.length;
```
after
```
const args = commander.rawArgs.slice(3);
```
This will falsify `valueIndex < srvArgs.length` condition that by default should be false.
Also replace:
```
spawnProcess("client", commander.rawArgs.slice(3));
```
with
```
spawnProcess("client", commander.rawArgs.slice(3).filter(arg => !arg.includes("server")));
```

**Comment by toddw** [comment]
Tested latest v1 branch and it now works
