### ISSUE TITLE
[v1] autoUpgrade throws error

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#532]
# Bug
An error is thrown when running `gluestick start` on an app with outdated dependencies, after agreeing to the upgrade. Yarn seems to do it's install and then an error is thrown.

### Reproduction Steps
1. `gluestick new gs-test123`
2. `cd gs-test123`
3. edit package.json and change the version of any of the packages to an older version, like `webpack 2.2.0` to `webpack 2.0.0`
4. `gluestick start`
5. Agree to prompt

### Current Result
Once yarn finishes with the install the following error is thrown:
```(node:56802) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: installProcess.on is not a function```

### Expected Result
No error to be thrown

**Comment by michalchudziak** [comment]
I've tried to reproduce this issue on OSX Sierra 10.12.3 and I've failed.

Everything seems to be working as intended:

![image](https://cloud.githubusercontent.com/assets/7837457/22652041/31b4a574-ec85-11e6-815d-4cb2b06f0e21.png)

Can you try cleaning the project and maybe give us some more details about device you use if it still persist?

**Comment by toddw** [comment]
Maybe it's my version of node `6.9.4`

**Comment by toddw** [comment]
Updated to `7.5.0` and I am still getting an error.
![image](https://cloud.githubusercontent.com/assets/140000/22670383/b6a94044-ec7d-11e6-9077-172ab440908a.png)

**Comment by toddw** [comment]
MacBook Pro (Mid 2014)
macOS Sierra 10.12.3
