### ISSUE TITLE
Integrate CLA bot.

### ISSUE THREAD

**Issue by michalchudziak** [TrueCar/gluestick#534]
I think this one will be the best solution https://github.com/clabot/clabot

**Comment by lukewalczak** [comment]
Hey @toddw - if we want to integrate `cla-bot` we need some basic hosting. Could you set up free plan on Heroku for this case?

**Comment by grabbou** [comment]
You can set one up with `now.sh` @lukewalczak for time being.

**Comment by toddw** [comment]
`now.sh` looks really cool! I'm asking the right people what TrueCar wants to use and I'll let you know as soon as they get back to me

**Comment by lukewalczak** [comment]
Finally it works ! Check PR #580, by mistake I compare v2 with develop but it doesn't matter (it's just an example PR -don't merge). Creating PR generate a message from clabot with link to formular. Formular contains your CLA tamplate. 
First `[clabot:check]` is before signing, second after filled the form.

**Comment by toddw** [comment]
awesome, nice work @lukewalczak
