### ISSUE TITLE
Debug tests for generated app is broken

### ISSUE THREAD

**Issue by ferrannp** [TrueCar/gluestick#535]
- In V1 debug generate tests works
- We might need to move `test` command into `gluestick-cli`

**Comment by zamotany** [comment]
Also, projects that use for example aphrodite use browser stuff like `document` so when debugging those variables might not be defined.

**Comment by zamotany** [comment]
Some refs:
https://github.com/facebook/jest/issues/1652
https://github.com/nodejs/node/issues/7593

**Comment by zamotany** [comment]
Fixed in node `8.4.0`+
