### ISSUE TITLE
Be able to pass any CLI option to gluestick test (Jest)

### ISSUE THREAD

**Issue by ferrannp** [TrueCar/gluestick#538]
Jest has all these options http://facebook.github.io/jest/docs/cli.html.

Right now we are limiting this to our debug `-D`, `--watch`, `--coverage` and our own pattern `-R` to simulate `jest -- TestName`. 

It would be nice to be able to use `gluestick test` exactly as if you were using `jest` without having to rewrite all the commands.

**Comment by toddw** [comment]
An api that mimics `npm run` would probably work pretty well `gluestick test -- …args`
