### ISSUE TITLE
Clean up generated project

### ISSUE THREAD

**Issue by pawlucci** [TrueCar/gluestick#576]
Branch: `576-clean-up-generated-project`

- [x] Fix Code Style (check Eslint) @ferrannp
- [x] Set up Flow + no errors @ferrannp
- [x] Review Flow (types) for generated files + add typing to tests (it already uses `flow-typed` from gluestick so we just need to add the headers and maker sure everything is ok) @ferrannp
- [x] Clean up and use dependencies @mike866 
- [x] Add scripts for Flow and Lint into `package.json` @ferrannp

**Comment by zamotany** [comment]
All stuff that are used by webpack should be included in dependencies, loaders etc (babel plugins and preset are used by loaders) + everything that is used in project like `react-helmet`
```
{
  "dependencies": {
    "babel-loader": "6.2.10",
    "babel-plugin-gluestick": "0.0.1",
    "babel-plugin-react-transform": "2.0.2",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-plugin-transform-flow-strip-types": "6.22.0",
    "babel-preset-es2015": "6.22.0",
    "babel-preset-react": "6.22.0",
    "babel-preset-stage-0": "6.22.0",
    "css-loader": "0.26.1",
    "file-loader": "0.10.0",
    "gluestick": "file:///Users/paweltrysla/Documents/gluestick/packages/gluestick",
    "optimize-css-assets-webpack-plugin": "1.3.0",
    "postcss-calc": "^5.3.1",
    "postcss-custom-properties": "^5.0.1",
    "postcss-loader": "^1.2.1",
    "react-helmet": "4.0.0",
    "react-hot-loader": "1.3.1",
    "react-loader": "2.4.0",
    "react-transform-hmr": "1.0.4",
    "style-loader": "0.13.1",
    "svg-react-loader": "0.3.7",
    "url-loader": "0.5.7",
    "radium": "0.18.1"
  },
  "devDependencies": {
    "babel-eslint": "7.1.1",
  }
}
```

**Comment by ferrannp** [comment]
What should we do with `.eslint` for generated project? It uses old template (like `gluestick` used to).

Should we change it? That can break a lot of rules for old apps (I assume a lot of them can be fix using `--fix` though).

@toddw @mike866

**Comment by toddw** [comment]
New apps should use the new one in gluestick, but it should let people update it to their own needs. So old apps don't need to update .eslintrc

**Comment by ferrannp** [comment]
@toddw mmm but, when you for example `generate` a new component, that component needs to use a template that respects the eslints rules. If we change it, old apps that generate elements will fail linting.

**Comment by toddw** [comment]
Oh yeah good point! Can you create a codemod to convert existing code bases? This upgrade is already intense with the test refactor. If we have to manually update listing rules in every file, people are going to be pretty frustrated. If we can automate it then it won't be too bad.

**Comment by toddw** [comment]
https://github.com/jlongster/prettier should be able to help with this

**Comment by toddw** [comment]
Even better https://github.com/kentcdodds/prettier-eslint
