### ISSUE TITLE
eslint config for generated app

### ISSUE THREAD

**Issue by ferrannp** [TrueCar/gluestick#592]
We wanted to update eslint config for generated app the same way we did with Gluestick. However, this would be a pretty big chance for people if they need to fix all rules manually.

We could try doing it but also use https://github.com/jlongster/prettier & https://github.com/kentcdodds/prettier-eslint

Discussion taken from #576

**Comment by zamotany** [comment]
Closing this, as it won't be an issue once presets will land #992
