### ISSUE TITLE
[v2] Typo in generator for new project

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#613]
https://github.com/TrueCar/gluestick/blob/v2/packages/gluestick/src/generator/predefined/new.js#L213

`ContaineHome` should be `ContainerHome`

**Comment by zamotany** [comment]
`ContainerHome` or should it be `HomeApp` because associated container for this test is `HomeApp.js`?

**Comment by toddw** [comment]
Oh yeah, then likely HomeApp, I just saw the missing `r`. I didn't read the code well enough to know if it was just the wrong name entirely

**Comment by zamotany** [comment]
Merging #612 will solve this issue.
