### ISSUE TITLE
[v2] We should include a generator for creating new entrypoints or "apps"

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#627]
# Feature Request
I love the new file/folder structure for entrypoints/apps in the v2 branch. It would be nice if we could add a generator for generating a new entrypoint.

Should we be calling them entrypoints or apps? Is everyone okay with this shared naming scheme or should we standardize on one?

**Comment by ferrannp** [comment]
This is merged. It is not in the README yet but it can be used using:
```
gluestick generate app some-name
```

Then we can also use generators in the new app:
```
gluestick generate component MyComponent -E apps/some-name
```
