### ISSUE TITLE
[v2] `gluestick test --watch` throwing errors

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#629]
# Bug
I'm getting errors when I try to use `gluestick test --watch`

## Reproduction steps
1. `gluestick new my-app --dev ../gluestick/packages/gluestick`
2. `cd my-app`
3. `gluestick test --watch`

## Current Result
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: resolve_projpath: path `/Users/twilliams/dev/gs-v1/test` does not exist
    at BunserBuf.<anonymous> (/Users/twilliams/dev/gs-v1/node_modules/sane/node_modules/fb-watchman/index.js:95:23)
    at emitOne (events.js:96:13)
    at BunserBuf.emit (events.js:188:7)
    at BunserBuf.process (/Users/twilliams/dev/gs-v1/node_modules/sane/node_modules/bser/index.js:289:10)
    at /Users/twilliams/dev/gs-v1/node_modules/sane/node_modules/bser/index.js:244:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

## Expected Result
No errors and Jest to run in watch mode

**Comment by zamotany** [comment]
Removing `test` from https://github.com/TrueCar/gluestick/blob/v2/packages/gluestick/src/commands/test.js#L33 will fix this but we lose support for older projects.
Hotfix is to run `mkdir test`.
Maybe detect if project is the newer one or the older one and add/ski `test` to `testPathDirs` depending on this?

**Comment by ferrannp** [comment]
I think the problem is that `testPathDirs` does not exist in Jest 19 anymore, instead, should be `roots`.

**Comment by ferrannp** [comment]
To me this is a bug from Jest. If you do not run watch mode, even if `test` folder does not exist, everything is fine. It should behave the same with `watch`. I will probably open an issue to them.

In the meantime, I'll make a fix of checking if adding `test` to `roots` only if that folder exists.
