### ISSUE TITLE
[v2] server side rendering issue with initial state

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#640]
# Bug
After creating a reducer with an initial state with an array of strings, the server side rendering doesn't seem to be able to read the strings for some reason. Instead it sees `undefined`

## Reproduction Steps
1. `gluestick new gs-state-bug --dev ../gluestick/packages/gluestick`
2. `cd gs-state-bug`
3. `gluestick generate reducer todos -E apps/main`
4. Update _src/apps/main/reducers/todos.js_ to look like the following:
```
/* @flow */

type State = Array<string>;

const INITIAL_STATE: State = ["first item", "second item"];

export default (state: State = INITIAL_STATE, action: { type: string, payload?: any }) => {
  switch (action.type) {
    default:
      return state;
  }
};

```
5. Update _src/apps/main/components/HomeApp.js to look like the following:
```
/* @flow */

import React, { Component } from "react";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";
import Helmet from "react-helmet";

import Home from "../components/Home";

export class HomeApp extends Component {
  props: {
    todos: Array<string>
  };

  render () {
    console.log("### PROPS", this.props.todos);
    return (
      <div>
        <Helmet title="Home" />
        <Home />
      </div>
    );
  }
}

export default connect(
  (state) => ({todos: state.todos}),
  (dispatch) => bindActionCreators({/** _INSERT_ACTION_CREATORS_ **/}, dispatch)
)(HomeApp);


```
6. `gluestick start`
7. visit http://localhost:8888/ in your browser and look at the console.log result in the terminal vs in the browser.

## Current Result
The terminal, or the console.log triggered from the server side rendering shows `undefined`. It is inconsistent with what the browser sees.
![image](https://cloud.githubusercontent.com/assets/140000/23238520/25e4b09c-f917-11e6-9164-651365e583db.png)

## Expected Result
The server side code should read the initial state in the same way that the browser does.

**Comment by toddw** [comment]
I am still able to reproduce this bug on the latest `v2` branch. This is a blocker for the RC1

**Comment by zamotany** [comment]
Root reducer for app must return object with all reducers mapping to it keys:

`reducers/index.js`:
```
import todo from './todo';
export default {
  todo,
}
```

And in `src/entires.json` reducers property must point to `reducers/index.js`.

**Comment by zamotany** [comment]
Here's repo with project with initial state:
https://github.com/zamotany/gluestick-test-app-initial-state/tree/master/src

**Comment by toddw** [comment]
This should be automated just like it is in the 0.10.x versions.

**Comment by toddw** [comment]
Instead of importing the reducer and then manually exporting it, couldn't we 'export { default as todos } from "./todos";'

**Comment by toddw** [comment]
If we can automate the way you showed, I'm fine with that too

**Comment by toddw** [comment]
Just saw https://github.com/TrueCar/gluestick/pull/676/files which looks like that's what you are doing. I'll try it out, thanks for the update!

**Comment by zamotany** [comment]
I had problems with
```
export { default as todos } from "./todos";
```
probably due to the fact that client was using ESM and server commonjs  and require was returning undefined.and at the top was webpack.

**Comment by toddw** [comment]
> probably due to the fact that client was using ESM and server commonjs and require was returning undefined.and at the top was webpack.

**Comment by toddw** [comment]
> probably due to the fact that client was using ESM and server commonjs and require was returning undefined.and at the top was webpack.

Is this going to cause issues elsewhere? Should we document that you cannot use `export { default as x }… ` in gluestick apps?

**Comment by zamotany** [comment]
I encountered this issue only here, we try to support both ESM and commonjs whenever possible like for instance in `src/gluestick.plugins.js`.
