### ISSUE TITLE
Integration/e2e test plan

### ISSUE THREAD

**Issue by ferrannp** [TrueCar/gluestick#643]
This is a placeholder for an integration/e2e test plan. We need to figure out what can we test.

**Comment by ferrannp** [comment]
We want to run this only when merging `next to staging` or submitting a PR to `staging`.

**Comment by toddw** [comment]
👍we've been wanting to do something like this for a long time. Very happy to see this issue

**Comment by zamotany** [comment]
Testing scenarios here: https://github.com/TrueCar/gluestick/issues/789

**Comment by zamotany** [comment]
E2E are set up and working, release `1.4.0`was the first one to have them run.
