### ISSUE TITLE
[v2] gsBeforeRoute no longer works

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#686]
`gsBeforeRoute` doesn't actually do anything anymore.

If a static function exists on a top level container that is referenced by a route, it used to run that function before rendering. This would run on the server side or in the browser depending on how you get there. Not only that but if it returns a promise it would wait for the promise to get resolved before continuing.

I think the following things were just never hooked up:
https://github.com/TrueCar/gluestick-shared/blob/master/src/lib/route-helper.js
https://github.com/TrueCar/gluestick-shared/blob/master/src/components/TransitionHooks.js

**Comment by toddw** [comment]
I'm also happy to rename this to something better… any suggestions?

**Comment by dratwas** [comment]
I didn't change the name because I won't touch gluestick-shared.  We need to remember that the hooks will not be called on init. Those hooks will be called only when we change a route.

**Comment by toddw** [comment]
Testing this out and it doesn't seem to be working

**Comment by toddw** [comment]
Example project https://github.com/toddw/gluestick-v1-testing

**Comment by zamotany** [comment]
This is not working or `rc-3` but working on `next` branch. Once #690 is settled out we will release new version.

**Comment by toddw** [comment]
I tried it on the next branch and it didn't seem to be working. Can you try the example project I posted

**Comment by zamotany** [comment]
I used your example project:
1. modified `package.json` and set `gluestick` to (in my case) `../gluestick/packages/gluestick`
2. `gluestick reinstall-dev`
3. `gluestick start`
then removed code in `componentDidMount` from `TodoApp` (gluestick rebuilded that).
Next, added some elements to list and refreshed page, even I opened it in incognito mode and I could see the list.

**Comment by toddw** [comment]
I wasn't seeing the update because I was updating gluestick-cli and not the gluestick package. Still getting used to the new setup. Thanks for verifying. publishing 1.0.0-rc.4 now
