### ISSUE TITLE
Automatically updating packages

### ISSUE THREAD

**Issue by pawlucci** [TrueCar/gluestick#688]
When we will have CircleCI deployment section setup, it will run `lerna publish` which will update version and publish to npm, then it will create docker image and push it, so everything will be fine, however in code (on github) we won't see those version updated. To overcome that small issue, we need to have repo owner user key set up, so we can push commits from circle ci to the repo.

**Comment by toddw** [comment]
A couple of lines that might need attention when getting this to work: https://github.com/TrueCar/gluestick/blob/v2/packages/gluestick/src/generator/templates/package.js#L10

https://github.com/TrueCar/gluestick/blob/v2/packages/gluestick-cli/new.js#L34

**Comment by ferrannp** [comment]
This is done in rc7.
