### ISSUE TITLE
Manual vs automatic deployment

### ISSUE THREAD

**Issue by zamotany** [TrueCar/gluestick#690]
Automatic deployment from Circle CI are fully possible, but they require some changes:
- repo owner user key to have write access to repo #688 
- make release branch (eg `release`) the default branch, otherwise Circle CI won't trigger any build unless there's PR associated with this branch

However setting release branch the default one, will make every externall PR's base branch to it, which is not ideal, since default branch should be working (dev) branch. Plus with manual deployment packages admin have the last word, so if sth is not right, packages won't be published.
If we will chose manual deployment, I will write script to automate publishing, tagging, commiting, building and pushing docker image, so it will be single command to run everything.

What do you think?
@toddw @cybrass

**Comment by toddw** [comment]
Is this a limitation of Circle CI? Can it be configured to build `develop` branch?

**Comment by zamotany** [comment]
In repo setting on Cricle CI we've set to build only PR, however the default branch (right now is develop) will always trigger build with every commit. So nothing is limiting. There are just 2 approaches, one make `release` the default branch, so we will have autodeployments, but every externall PR (made by someone else apart from TrueCar, or Callstack) will have base set to `release`, which is not ideal.

**Comment by zamotany** [comment]
I will prepare deploy script and now we will be spawning it locally, then moving it to circle CI will be just a matter of adding 1 line providing we will agree to use Circle CI.

**Comment by zamotany** [comment]
One big advantage of deployment on Circle CI which at the same time is huge drawback of deploying from local machine is that, when new packages are added, the person who push it is the owner, so there will be multiple packages starting with `gluestick` which have different authors. If we publish packages from Circle CI with the same token, not only every package will have the same author, but also we won't have permissions issues - the one with Error 403.
