### ISSUE TITLE
[1-rc.3] Did we lose the ability to set the status code in our apps?

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#694]
I noticed some commented out code that is used by some of our apps:
https://github.com/TrueCar/gluestick/blob/v2/packages/gluestick/src/renderer/middleware.js#L108

Does this mean we lost the ability to set the status code the way we did before? Is this because there is a new better way to do it? If not, then we need to be able to do that.

**Comment by zamotany** [comment]
#695
