### ISSUE TITLE
Gluestick dockerize not working

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#715]
In 0.10.x when we publish a new version of GlueStick we would also publish a new version of our base docker container that `gluestick dockerize` is based off of. This base image is used when you run `gluestick dockerize container-name`. It seems like none of this is hooked up in the current release candidate.

# Notes
**This needs to be merged into the 1.0.0-rc branch**

**Comment by zamotany** [comment]
This is connected with #690. Once this is figured out, I will add code to push to Docker Hub in `circle.yml` (if automatic) or to `deploy.sh` script (if manual).

**Comment by marcdel** [comment]
Hola, y'all. Should new Gluestick releases be generating new docker images now?

I'm still getting `manifest for truecar/gluestick:1.0.0-rc.11 not found` when Jenkins tries to dockerize. I only see rc.4 on docker hub (I assume that's where it's pulling from?) https://hub.docker.com/r/truecar/gluestick/tags/.

It's also possible that my Jenkins build configuration is out of date though, or something is wrong on that end: http://jenkins.true.sh:8080/job/ep-ui/configure.

**Comment by zamotany** [comment]
To be honest I have no idea why there's 1.0.0-rc.4 on Docker Hub since, we haven't pushed docker image with gluestick release candidates. So this error you're getting is ok. We have docker image deployment section in deploy script, however none of the persons who can publish packages to npm, have docker installed.

**Comment by toddw** [comment]
I manually published 1.0.0-rc.4 on docker hub. We need to make sure this is automated again

**Comment by ferrannp** [comment]
This needs to be tested.

**Comment by zamotany** [comment]
Turns out, email for docker deploy account must be set in CircleCI settings, without it deploy will fail.

**Comment by zamotany** [comment]
I've tested this command with `1.3.0` and it's working. You might need to run `gluestick auto-upgrade` firstly to update `.Dockerfile`.

**Comment by toddw** [comment]
:party: stoked
