### ISSUE TITLE
Add hooks for express app

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#716]
In Sprint 1 we added the ability to expose the underlying express app. Is this still possible? Can someone show an example?

Sprint 1 issue: https://github.com/TrueCar/gluestick/issues/355

**Comment by zamotany** [comment]
@dratwas I think we don't have hook for express app. We need to add it, probably it will be called once, when express app is creted.

**Comment by zamotany** [comment]
Merged PR: #724
