### ISSUE TITLE
installing gluestick vs gluestick-cli globally

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#730]
After splitting the project into multiple modules there seems to be confusion around installing gluestick globally.

- `npm install gluestick@1.0.0-rc.4 -g` will install a global `gluestick` binary but it does not work.
- `npm install gluestick-cli@1.0.0-rc.4 -g` will also install a global `gluestick` binary and this does work.

~Is there a way for `gluestick@1.0.0-rc.4` to install the `gluestick-cli` binary? If not, is it possible so that it doesn't make any binary public at all? This is going to cause a lot of confusion for people who are used to install `gluestick` and not `gluestick-cli`~

# Proposal [added after discussion below]
When someone installs `gluestick` instead of `gluestick-cli` and runs the `gluestick` binary, we should show a helpful message that prompts them to install `gluestick-cli` instead.

**Comment by zamotany** [comment]
`gluestick` should be not installed globally, this may results in undesired behaviour. Only `gluestick-cli` can be global. Plus if we remove binary from `gluestick` apart from a lot of code being broken, we lose ability to export code via requires. Right know we can have binary file and export **other** code via `require('gluestick');`. Currently we are not using this feature, but we planned to replace requiring `gluestick-shared` with `gluestick`.

**Comment by toddw** [comment]
> gluestick should be not installed globally, this may results in undesired behaviour. Only gluestick-cli can be global.

**Comment by toddw** [comment]
> gluestick should be not installed globally, this may results in undesired behaviour. Only gluestick-cli can be global.

Is it possible to detect if `gluestick` is being run from `gluestick` and not `gluestick-cli` and give a helpful message like "It looks like you installed `gluestick` globally when you should have installed `gluestick-cli`"? I'm sure that sentence can look better but is it possible without too much work?

**Comment by zamotany** [comment]
Yes, it's possible.

**Comment by toddw** [comment]
I'll edit this issue
