### ISSUE TITLE
[1.0.0-rc.4] gluestick start -P fails

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#731]
# Bug
Running `gluestick start -P` returns and fails to start the server without any error message.

# Notes
**The fix for this should be merged into the `1.0.0-rc` branch**

## Steps to reproduce
In a newly generated app:
1. `NODE_ENV=production gluestick build`
2. `NODE_ENV=production gluestick start -P`

## Current result
it just returns without doing anything

## Expected result
The app should start running in production mode

**Comment by zamotany** [comment]
For the assignee: https://github.com/TrueCar/gluestick/blob/next/packages/gluestick/src/commands/start.js#L32-L64
