### ISSUE TITLE
[1.0.0-rc] did we lose init.server.js capability?

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#732]
Did we lose the ability to include _init.server.js_. I do see init.browser.js but it looks like we may have lost _init.server.js_

https://github.com/TrueCar/gluestick/blob/develop/src/entrypoints/server.js#L9-L16

# Notes
**This is needed in the 1.0.0-rc branch**

**Comment by zamotany** [comment]
We decided that it will be in `gluestick.hooks.js` as the rest, because keeping it in separate file is pointless and involves more changes than adding it as hook. Besides it's more consistent to have every hooks in one place.

**Comment by toddw** [comment]
How do you feel about adding `postStart`? or is there already something for that? There are times when people need to run a script when they run `gluestick start` before the server is initiated. That is where our init.server.js code mostly came into play. We don't really want the code to run before every render but just once when the app starts off

**Comment by zamotany** [comment]
It won't run with every render. It will run right before renderer code starts. The question is should this be run once when gluestick start is called or on every **rebuild and rerun** in dev mode.

**Comment by toddw** [comment]
It should run once per build
