### ISSUE TITLE
[1.0.0-rc] apps/entrypoints are returning 404

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#735]
# Bug
There seems to be a bug with entry points where they show up as 404 not found

## Reproduction Steps
1. `gluestick new gs-app`
2. `cd gs-app`
3. `gluestick generate app used`
4. `gluestick start`
5. open browser to [http://localhost:8888/used](http://localhost:8888/used)

## Current Result
404 not found

## Expected Result
Expected to see HomeApp/Home component to open up at the /used route

# Notes
**The resolution for this needs to be merged into 1.0.0-rc branch**

**Comment by zamotany** [comment]
`routes.js` in `used` must be updated, because index route points to `/`
