### ISSUE TITLE
Remove gluestick-shared package and integrate it into gluestick

### ISSUE THREAD

**Issue by ferrannp** [TrueCar/gluestick#741]
Right now generated app depends on `gluestick` and `gluestick-shared` (that actually lives inside `gluestick`) <-- see `next` branch.

`gluestick-shared` code can just be included into `gluestick` so generated app will just need 1 dependency.

Any thoughts against this?

**Comment by zamotany** [comment]
In production gluestick-shared is not a dependency of project, so only gluestick is installed. In dev mode however, all packages are installed, to prevent npm from pulling down gluestick packages from registry.
