### ISSUE TITLE
[rc] Issues when running npm publish

### ISSUE THREAD

**Issue by ferrannp** [TrueCar/gluestick#759]
I have permissions to publish to `npm`. It looks like rc6 was correctly published https://www.npmjs.com/search?q=gluestick but I got different errors.

1. About docker: `sh: ./docker/create-base-image.js: No such file or directory` so docker image was not successfully created
2. Some strange error: `npm ERR! "You cannot publish over the previously published version 1.0.0-rc.6." : gluestick`

I attach [publish-error.txt](https://github.com/TrueCar/gluestick/files/825848/publish-error.txt) the full stacktrace.

Moreover, the auto commit was done https://github.com/TrueCar/gluestick/commit/70b4c206ce65bd77ca380ca0e0603f32e4c5acc1 (updating gluestick versions). But, the dependency inside `gluestick` (it has `gluestick-shared` as dependency), was **not** updated https://github.com/TrueCar/gluestick/blob/staging/packages/gluestick/package.json#L59.

**Comment by zamotany** [comment]
About 1: it looks like there is `postpublish` or sth like that in gluestick that sill wants to exec `./docker/create-base-image.js` which I removed.
