### ISSUE TITLE
gluestick start --run-tests

### ISSUE THREAD

**Issue by lukewalczak** [TrueCar/gluestick#780]
### Bug
![image](https://cloud.githubusercontent.com/assets/22746080/23797038/3b4fca6e-059e-11e7-841b-a40e32dbbd04.png)

## Reporduction steps
on branch `mike866/generators-package`
`gluestick start --run-tests`

## Expected result
No error

**Comment by michalchudziak** [comment]
Can you quickly check if it's present on `next` as well?

**Comment by zamotany** [comment]
Yes, it will be it's because `--run-tests` is passed to `start-client` and `start-server` which doesn't have that option

**Comment by michalchudziak** [comment]
I think we can add those filters and close it after #679 since I've changed filtering a bit here.
