### ISSUE TITLE
gluestick-config-legacy custom aliases doesn't work with CSS files

### ISSUE THREAD

**Issue by lukewalczak** [TrueCar/gluestick#788]
### Bug
![image](https://cloud.githubusercontent.com/assets/22746080/23850493/0738ef00-07e0-11e7-84fa-3af9443f259d.png)

## Reproduction steps
1. Installed `gluestick-config-legacy` in new generated app:
`npm install ../gluestick/packages/gluestick-config-legacy`
2. Added in `src/gluestick.plugins.js`:
```
export default [
  'gluestick-config-legacy'
]
```
3. Added alias in `additionalAliases`:
```
  additionalAliases: {
    abc: ["src"]
  },
```

4. Changed path to file `Home.css` in `Home.js` using alias:
`import "abc/apps/main/components/Home.css";`
## Expected result
No error

**Comment by zamotany** [comment]
Custom aliases with CSS files results with `module not found` error only on renderer. In renderer bundle import with to that file appears to be re-export from `node_modules`, so webpack/universal-webpack treats it like a external module. However after applying inline loaders renderer bundle fails in other place.

However, when using already existing (predefined) alias with CSS file, it works perfectly.

**Comment by zamotany** [comment]
So the issue is probably because custom aliases are set after everything is compiled, so universal-webpack doesn't mark custom aliases as non-externals.
