### ISSUE TITLE
Testing scenarios for E2E tests

### ISSUE THREAD

**Issue by zamotany** [TrueCar/gluestick#789]
TODO:

- [x] Generate new project in dev mode with npm
- [ ] Generate new project in dev mode with yarn
- [x] `gluestick generate component` (default app)
- [x] `gluestick generate component` (specified app)
- [x] `gluestick generate component` (shared)
- [x] `gluestick generate container` (default app)
- [x] `gluestick generate container` (specified app)
- [x] `gluestick generate container` (shared)
- [x] `gluestick generate reducer` default app)
- [x] `gluestick generate reducer` specified app)
- [x] `gluestick generate reducer` (shared)
- [x] `gluestick generate generator`
- [x] `gluestick generate app` (camel case)
- [x] `gluestick generate app` (kebab case)
- [x] `gluestick destroy component` (from app)
- [x] `gluestick destroy component` (from shared)
- [x] `gluestick destroy container` (from app)
- [x] `gluestick destroy container` (from shared)
- [x] `gluestick destroy reducer` (from app)
- [x] `gluestick destroy reducer` (from shared)
- [x] `gluestick build`
- [x] `gluestick build` in production
- [x] `gluestick test` in project
- [x] `gluestick bin`
- [x] flow in project
- [x] lint in project

Not applicable to E2E tests:
- [ ] Generate new project with npm
- [ ] Generate new project with yarn
- [ ] `gluestick start` (not applicable to E2E tests)
- [ ] `gluestick start` in production (not applicable to E2E tests)
- [ ] `gluestick start` with tests (not applicable to E2E tests)
- [ ] `gluestick start` with skip build option (not applicable to E2E tests)
- [ ] debugging `gluestick start-server` (not applicable to E2E tests)

To discuss:
- [ ] radium plugin
- [ ] aphrodite plugin 
- [ ] config legacy plugin
- [ ] ENV expose AST plugin

**Comment by pawlucci** [comment]
@toddw can you please take a look at this testing flow and add things which we've missed?

**Comment by zamotany** [comment]
E2E tests ticket: https://github.com/TrueCar/gluestick/issues/789
