### ISSUE TITLE
Prepublish script to transpile gluestick

### ISSUE THREAD

**Issue by pawlucci** [TrueCar/gluestick#809]
With this, we will be able to get rid of: `require('compiled/gluestick'`) and similars (no need to use `compiled`).

And also, we can remove `transformIgnorePatterns` from `commands/test/test.js`.

We need a wait to still preserve Flow types when transpiling (there are article online about it).

**Comment by ferrannp** [comment]
@pawlucci & @mike866 I added more info about this. Also, I think this should be moved to `Release Candidate` sprint.

**Comment by ferrannp** [comment]
Possibly related to #880.

**Comment by zamotany** [comment]
Closed #990
