### ISSUE TITLE
Update Getting Started

### ISSUE THREAD

**Issue by mateomurphy** [TrueCar/gluestick#81]
I'm trying out gluestick by following the getting started guide at https://www.drivenbycode.com/getting-started-with-gluestick/, but I'm running into some issues, as it seems to be out of date:

The first issue is that generating the todos.js reducer also generates a test, that then fails when the initial state is changed. I tried to get the test pass by updating it:

```
import reducer from "reducers/todos";

describe("reducers/todos", () => {
  it("returns the initial state", () => {
    expect(
      reducer(undefined, {})
    ).to.equal(["First Item", "Second Item"]);
  });
});

```

But this fails with `AssertionError: expected [ 'First Item', 'Second Item' ] to equal [ 'First Item', 'Second Item' ]` and I have no idea how to debug that.

The second is that I can't get hooking up your data to work. The generated Todos container is not the same as in the guide, and pasting in the version in the guide leads to another test failing, with: `Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`

**Comment by toddw** [comment]
Thanks @mateomurphy, you are correct, we need to update our getting started guide. We will start in on that.

> But this fails with AssertionError: expected [ 'First Item', 'Second Item' ] to equal [ 'First Item', 'Second Item' ] and I have no idea how to debug that.

When you are comparing objects or arrays, you need to use `…).to.deep.equal(…)` http://chaijs.com/api/bdd/#method_deep

> Violation: Element type is invalid: expected a string (for built-in components) or a class/function 

This error is almost always because you didn't `export default` in your file. If you were converting from the new container back to the old style container with the `@connect` decorator. My guess would be that your class definition is still `export class` when it should be `export default class`. That being said, I highly recommend you use the new version as it is going to be much easier to test your containers using the non connected version. Also, we are pumping the breaks on our usage of decorators while the spec gets more defined and babel support gets stronger.

Please, let me know if that helps…

**Comment by mateomurphy** [comment]
> When you are comparing objects or arrays, you need to use …).to.deep.equal(…) http://chaijs.com/api/bdd/#method_deep

Thanks, I figured it was something like that but not being familiar with Chai I couldn't find it.

> This error is almost always because you didn't export default in your file

Actually I copied the exact code from the guide, and the `export default` is there. I also tried modifying the new version, so that it looks something like this

```
/* @flow */
import React, { Component, PropTypes } from "react";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

import TodoList from "../components/TodoList";

export class Todos extends Component {
  /**
   * Called by ReactRouter before loading the container. Called prior to the
   * React life cycle so doesn't have access to component's props or state.
   *
   * @param {Object} store redux store object
   * @param {Object} renderProps render properties returned from ReactRouter
   * @param {Object} query location data
   * @param {Object} serverProps server specific properties
   * @param {Boolean} serverProps.isServer method running on server or not
   * @param {Request} [serverProps.request] express request if isServer
   *
   * @return {(Promise|undefined)} If this method returns a promise, the router
   * will wait for the promise to resolve before the container is loaded.
   */
  static gsBeforeRoute ({dispatch}, renderProps, query, serverProps) {}

  render () {
    return (
      <TodoList todos={this.props.todos} />
    );
  }
}

export default connect(
  (state) => ({todos: state.todos}),
  (dispatch) => bindActionCreators({/** _INSERT_ACTION_CREATORS_ **/}, dispatch)
)(Todos);
```

But I am missing something because  `this.props.todos` is undefined.

**Comment by toddw** [comment]
What does your reducer look like? Is it still undefined after a browser refresh?

**Comment by mateomurphy** [comment]
Reducer looks like:

```
/* @flow */
const INITIAL_STATE = ["First Item", "Second Item"];

export default (state=INITIAL_STATE, action) => {
  switch (action.type) {
    default:
      return state;
  }
};
```

But it doesn't actually get called

**Comment by mateomurphy** [comment]
I've published a repository containing my code here https://github.com/mateomurphy/gluestick-example-app, should be easier to see the problem that way

**Comment by toddw** [comment]
You are right @mateomurphy! When we upgraded to babel 6, we introduced a bug that broke the store. This PR fixes that https://github.com/TrueCar/gluestick/pull/90

It has been merged and published. Please try the latest version of GlueStick and see if you still have any issues.

**Comment by mateomurphy** [comment]
Hi, yes it works now! I will run through the rest of the guide and see if any other issues come up. Thanks

**Comment by mateomurphy** [comment]
Looks good for now, closing. Thanks!

**Comment by toddw** [comment]
Stoked! Thanks for pointing out the bug
