### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by pawlucci** [TrueCar/gluestick#812]
Missing tests:

- [ ] gluestick-cli
- [ ] gluestick/src/cli/helpers
- [x] gluestick/src/cli/execWithConfig @zamotany
- [ ] gluestick/src/commands/build
- [ ] gluestick/src/commands/dockerize
- [x] gluestick/src/commands/start @zamotany
- [x] gluestick/src/commands/start-client @zamotany
- [ ] gluestick/src/commands/start-server/*
- [x] gluestick/src/commands/test/test @zamotay

Low code coverage:
- [ ] gluestick/src/commands/bin
- [ ] gluestick/src/commands/destroy
- [ ] gluestick/src/plugins/utils
- [ ] gluestick/src/renderer/entry

**Comment by zamotany** [comment]
No longer relevant. If you want to imporve coverage:
1. Go to https://github.com/TrueCar/gluestick/commits/next and from the latest commit click green check icon.
2. Click **Artifacts** tab.
3. Unfold to ` Container 0/home/ubuntu/gluestick/coverage/lcov-report/` and click `index.html`.
