### ISSUE TITLE
Consider using fast-sass-loader and/or happypack

### ISSUE THREAD

**Issue by pawlucci** [TrueCar/gluestick#814]
- [x] :x: `fast-sass-loader` - degrades performance in some most cases, should be specified manually in `src/webpack.hooks.js`
- [ ] ❓ `happy-pack`
- [ ] ❓ remove `image-webpack-loader` - approx. 1% faster build in ~3000 module project

**Comment by zamotany** [comment]
Closed, due to happy-pack providing almost no performance gain in webpack2.
