### ISSUE TITLE
Generating reducer with dash in path generates invalid import statement

### ISSUE THREAD

**Issue by marcdel** [TrueCar/gluestick#840]
#Bug

If you generate a reducer with a `-` in the path, the import statement added to `reducers/index.js` is invalid syntax.

# Reproduction Steps

* `gluestick generate reducer somewhere/myReducer`
* `gluestick generate reducer path-to/myReducer`
* `gluestick start`

# Current Result

```
import path-toMyReducer from "./path-to/myReducer";
import somewhereMyReducer from "./somewhere/myReducer";
```

```
./src/apps/main/reducers/index.js
Module build failed: SyntaxError: Unexpected token (2:11)

  1 | /* @flow */
> 2 | import path-toReducer from "./path-to/reducer";
    |            ^
  3 |
  4 | export default {
  5 |   path-toReducer,
```

# Expected Result

Presumably to be safe we'd want something like the following (though including the path in the name by default is kind of a bummer):

```
import pathToMyReducer from "./path-to/myReducer";
import somewhereMyReducer from "./somewhere/myReducer";
```

**Comment by toddw** [comment]
Thanks for catching this!
