### ISSUE TITLE
Changelog for 1.0.0

### ISSUE THREAD

**Issue by pawlucci** [TrueCar/gluestick#843]
What's been changed in v1 comparing to previous version.

**Comment by zamotany** [comment]
`gluestick` commands:
- refactored new command #708
- refactored build command #587 
- refactored bin command #494
- refactored generate command #472
- refactored destroy command #548
- refactored dockerize command #655 
- refactored start command #707 #608
- refactored start-client command #590
- refactored start-server command
- refactored test command with support for all Jest CLI options #775
- removed run command #604
- extracted auto upgrade feature from start command to spearate auto-upgrade command #816 #612

**Comment by zamotany** [comment]
`gluestick-cli` commands:
- added `watch` command for better gluestick development #504

**Comment by zamotany** [comment]
Misc:
- created generators API and extracted it into separate package #458 #712 
- created generators #842
- replaced `node-inspector` with `node --inspect` #445
- switched to yarn when creating new project #829
- disabled redux devtools in production #828
- migrated `gluestick-shared` to `gluestick` and export shared code from `gluestick` #815
- updated all dependencies #804 #671
- refactored gluestick tests #774
- added error message when `gluestick` installed globally #744
- refactored promise middleware and replaced `value` with `payload` #727
- added flow support for generated project #726
- refactored SSR server and middleware and added hooks #724 #649 #571
- added support for running single entrypoint or group #705
- removed `firefox` option #700
- improved home example #680
- refactored webpack configs to use with version 2 #544 
- restructured test directories #509
- added support for multiple apps #659 #647

**Comment by zamotany** [comment]
Plugins:
- created bunyan plugin for request/response logging #817
- created aphrodite plugin #714
- created radium plugin #682
- created plugin for automatically exposing env variables from AST #622
