### ISSUE TITLE
Separate dependencies (dev mode) from an app into vendors.js to speed up development

### ISSUE THREAD

**Issue by ferrannp** [TrueCar/gluestick#844]
It should add all `node_modules` dependencies into `vendor.bundle.js`. This is specially useful on dev mode using hot module reloading.

**Comment by zamotany** [comment]
From what I know, vendor bundle will be filled with common dependencies, which are used by multiple entry bundles. Vendor is not sued to store every `node_modules` dependency, but to only for those which are shared.

**Comment by ferrannp** [comment]
Right now in dev mode:

![screen shot 2017-03-23 at 13 13 43](https://cloud.githubusercontent.com/assets/774577/24247226/216cb2ec-0fcb-11e7-9a18-689e429d7679.png)

So everything is bloated into `healthCheck-[hash].js`. Same if you run `build` using production flag.

I get that `vendor.js` is used for common dependencies but it will be good also to split `node_modules` and app files from the same app. It will make development much faster.

**Comment by zamotany** [comment]
Show me the rest of the log

**Comment by ferrannp** [comment]
Something like:

```
apps/
  app1/
    app1.js
    vendor.js
  app2/
    app2.js
    vendor.js
vendor.js
```

Only issue I see with this is what happens with the common `vendor.js` if two apps share a dependency but a third one does not?

**Comment by zamotany** [comment]
Closing, since vendor DLL basically allow to do that.
