### ISSUE TITLE
Create alias for each app apart from "apps"

### ISSUE THREAD

**Issue by ferrannp** [TrueCar/gluestick#847]
It is quite repetitive to do something like `apps/main/components/`, we can do better and have an alias generated for each new app and then do `main/components`, etc. 

Of course depending on the app name you choose, you might create a conflict so I'd be good  we take this into consideration (like error alias already exist).

This is specially important to migrate internal apps .

**Comment by toddw** [comment]
That sounds good but I agree it could be risky. Do you think it would feel as repetitive in day to day app development? I'm wondering if it is just more painful while porting to v1?

I'm okay with making this change if you feel it makes the developer experience better

**Comment by zamotany** [comment]
The only risk that comes to my mind are situation when user will overwrite the default aliases by mistake. @todd do you have any othwr concers about it??

**Comment by toddw** [comment]
overwriting default aliases is a good one @zamotany. We could probably counter that by not allowing an app be named `shared` etc…?

**Comment by ferrannp** [comment]
Yup If you check my original message, I think we should not let them overwrite. So if they try to generate an app that already exists or `shared`, the alias should not be created and we could throw an error. WDYT?

**Comment by zamotany** [comment]
So I made an implementation when it will detect apps based on `src/entries.json` and it will be merged into alias object but the default aliases will overwrite the detected ones.
