### ISSUE TITLE
Discussion of shared folder

### ISSUE THREAD

**Issue by ferrannp** [TrueCar/gluestick#848]
I see that what we called `shared` here, internally we call it `common`.

I am thinking how "safe" is to reuse an action file or a reducer file ? Because then messing with that file might affect several apps. For sure having tests will make it safer but I am wondering about this pattern right now.

It would be nice to share thoughts.

**Comment by toddw** [comment]
I think we can move stuff from common into shared.

There are reducers that are used by multiple apps like loading a user's session doesn't change. It is risky to change those but it's worth it not to duplicate code in my opinion.

**Comment by ferrannp** [comment]
Ok, just wanted to double check 👍
