### ISSUE TITLE
Make gluestick-cli install last version of gluestick from npm.

### ISSUE THREAD

**Issue by michalchudziak** [TrueCar/gluestick#851]
We should aim to have same behaviour as `react-native-cli` so always the latest stable version of `gluestick` should be included in generated project.

**Comment by ferrannp** [comment]
Do you think we could also show a warning if you are using old version of `gluestick-cli`? Recently I discovered I was using a really old version of `react-native-cli` globally.

**Comment by zamotany** [comment]
`GET http://registry.npmjs.org/gluestick` and look for `dist-tags.latest`
