### ISSUE TITLE
Project fails to serve app if it's key is different from it's route path 

### ISSUE THREAD

**Issue by zamotany** [TrueCar/gluestick#857]
If app key eg `/profile` in `src/entries.json` is different than `path` for top-level route in `src/apps/profile/routes.js`, gluestick will fail to serve this app. 

Not sure if this is a bug. Do we need to remove that limitation?
@toddw 

There's not-so-bad workaround for this:
rename app key in `src/entries.json` to match `path` from routes and add `name` property

**Comment by toddw** [comment]
These seems like a reasonable limitation to me
