### ISSUE TITLE
Shall we not create apps/main when generating a new project?

### ISSUE THREAD

**Issue by ferrannp** [TrueCar/gluestick#864]
We saw in internal project we might not need an app called `main`. This will also make generating a new project faster.

If user wants an app called `main` later, it just need to call `gluestick generate app main`.

**Comment by zamotany** [comment]
This is fine for people who already know gluestick, but suppose you just have come across gluestick, you install it, create new app, type `gluestick start` and it doesn't work. This will add unnecessary sep for end user, so my suggestion is to generate main by default, but provide flag, sth like `--skip-main` or `--raw` or `--no-main` which if preset will tell gluestick not to generate main app.
