### ISSUE TITLE
Adding loaders to webpack-additions not working

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#867]
# Bug
additional webpack loaders doesn't seem to be working

## Reproduction steps
1. `gluestick new gs-file-loader`
2. `cd gs-file-loader`
3. Modify `additionalLoaders` in _src/config/webpack-additions.js_ to look like the following:
```
additionalLoaders: [
  {
    test: /\.txt$/,
    use: [
      {
        loader: "file-loader"
      }
    ]
  }
],
```
4. `echo "test 123" > src/apps/main/assets/test.txt`
5. Add the following line to the top of _src/apps/main/components/Home.js_
```
import testFile from "../assets/test.txt";
```
6. `gluestick start`

## Current Result
It generates an error when trying to import _test.txt_ instead of using the file loader.
```
./src/apps/main/assets/test.txt
Module parse failed: /Users/todd/dev/gs-file-loader/src/apps/main/assets/test.txt Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
| test 123
| 
@ ./src/apps/main/components/Home.js 19:12-41
@ ./src/apps/main/containers/HomeApp.js
@ ./src/apps/main/routes.js
@ ./gluestick/clientEntryInit/main.js
@ multi webpack-hot-middleware/client?path=http://localhost:8888/__webpack_hmr webpack/hot/only-dev-server babel-polyfill eventsource-polyfill ./gluestick/clientEntryInit/main.js
```

## Expected Result
It should have used `file-loader` and therefore returned a url to _test.txt_ instead of throwing an error.

**Comment by zamotany** [comment]
You need `gluestick-config-legacy` for that https://github.com/TrueCar/gluestick/tree/next/packages/gluestick-config-legacy

**Comment by toddw** [comment]
Is there a new way to add a loader that doesn't require the legacy plugin?

**Comment by zamotany** [comment]
Not really, we can add that support or make config legacy plugin to be installed by default

**Comment by toddw** [comment]
I thought we had a way to expose the webpack config before building but I don't see that anymore. Was that part of the old "v1"? If that exists still then that would work. Otherwise we should add this as a feature to GlueStick without needing a plugin. It doesn't need to follow the legacy format but there should be a way for people to modify the webpack config

**Comment by toddw** [comment]
original issue: https://github.com/TrueCar/gluestick/issues/407

**Comment by zamotany** [comment]
Maybe have `webpack.config.js` file living in `src` or `src/config` that will merge object exported from it or in case function is exported, it will pass prepared webpack config to it for modification. It will be a low level option to modify it, config legacy will be a high level?? WDYT??

**Comment by toddw** [comment]
That sounds good as long as we don't make it too easy to "remove" anything from _webpack.config.js_ that would break the app by mistake. If we are "merging" then I don't see this as a problem unless they overwrite something that breaks stuff. This is sort of a power feature so it doesn't have to be super defensive against mistakes.

In this scenario would you be able to easily _append_ to `module.rules`?

**Comment by ferrannp** [comment]
When this is done, we need to remember to remove this workaround https://github.com/TrueCar/gluestick/blob/70a4c882f37236c3ccfe42f28d2481881bd31473/packages/gluestick/src/config/webpack/webpack.config.js#L142-L146 and add it into the app directly instead of in gluestick.

---

Also, we are considering if we need `gluestick-config-legacy` at all or we just provide one way to do this which is having that `webpack.config.js` where we can add things and smartly override others.

**Comment by toddw** [comment]
I see `gluestick-config-legacy` as a nice migration plugin but long term I would like to deprecate it
