### ISSUE TITLE
Consider to use Prettier 

### ISSUE THREAD

**Issue by pawlucci** [TrueCar/gluestick#883]
As solution for the app (right now it is using old eslint config).

That might be more for gluestick than this project itself. Even that gluestick generates and eslintrc config when creating a new app, anybody can override it (like consumer-frontend app).

We could probably do less on eslint in favour of prettier. For example, eslint has nice warning for todo comments so you don't forget them in the future but for things like double/single quotes, prettier is more than enough.

**Comment by toddw** [comment]
:+1: absolutely I would like this
