### ISSUE TITLE
Flow errors on generated project

### ISSUE THREAD

**Issue by ferrannp** [TrueCar/gluestick#927]
In an internal project we can see:

```
node_modules/gluestick/generator/predefined/new.js:22
 22: const tag = require('../../package.json').version;
                                               ^^^^^^^ property `version`. Property not found in
 22: const tag = require('../../package.json').version;
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ String

node_modules/gluestick/src/commands/autoUpgrade/checkForMismatch.js:8
  8: const version = require('../../../package.json').version;
                                                      ^^^^^^^ property `version`. Property not found in
  8: const version = require('../../../package.json').version;
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ String

node_modules/gluestick/src/commands/new.js:49
 49:     spawn.sync('./node_modules/.bin/flow-typed', ['install', `jest@${packageJSON.dependencies.jest}`], { stdio: 'inherit' });
                                                                                      ^^^^^^^^^^^^ property `dependencies`. Property not found in
 49:     spawn.sync('./node_modules/.bin/flow-typed', ['install', `jest@${packageJSON.dependencies.jest}`], { stdio: 'inherit' });
                                                                          ^^^^^^^^^^^ String
```

Not sure why since when we generate a new app it seems fine so... We'll need to investigate this.

**Comment by zamotany** [comment]
It seems to me it's flow issue for the following reasons:
- no such flow issues in gluestick repo
- no flow issues when running e2e tests
- those files doesn't have flow types exported, flow should not check those files

**Comment by ferrannp** [comment]
> those files doesn't have flow types exported, flow should not check those files

What do you mean? Why would flow not check those files? They use `/* @flow */` so they will be checked. 

Try for example to add `const a: boolean = 2` in one of those files and you will see that a new generated app will throw a flow error.

But yeah the errors are not happening in generated app so we need to check in internal project what is going on that is causing this with `gluestick`.

**Comment by ferrannp** [comment]
So this problem turns out to be that the app using gluestick is mocking `json` in `module.name_mapper`. Not really a gluestick isssue. Closing.
