### ISSUE TITLE
Default Babel config doesn't allow for tree shaking / dead code elimination.

### ISSUE THREAD

**Issue by threehams** [TrueCar/gluestick#955]
The default Babel settings for a project don't include `{modules: false}`, so Babel converts ES6 imports to CommonJS. This prevents Webpack from marking unused modules for Uglify to remove (CommonJS can't be statically analyzed).

Whether this is called tree-shaking or dead code elimination (there is so much confusion around these terms), enabling this by default should allow us to bundle only what we need, while still being able to use destructuring with imports.

**Comment by threehams** [comment]
Article from two days ago finally explains this really, really well:
https://medium.freecodecamp.com/tree-shaking-es6-modules-in-webpack-2-1add6672f31b

**Comment by zamotany** [comment]
To get rid of warning add the following line to `src/config/redux-middleware.js`:
```
export const thunkMiddleware = null;
```
