### ISSUE TITLE
Use loadjs options from the app config in renderer/helpers/getAssetsLoader.js

### ISSUE THREAD

**Issue by sethbattin** [TrueCar/gluestick#971]
In PR https://github.com/TrueCar/gluestick/pull/373 we added the ability pull an app's config value for loadjs, and use it as options during the initial calls to loadjs: https://github.com/TrueCar/gluestick/pull/373/files#diff-c5d272a5013400b4f0a33eacb6ae3ca8R27 .  The config is still serialized in the 1.7.5 library, but it is not used in the loadjs call:  https://github.com/TrueCar/gluestick/commit/858dc5cac1b6974027897ce1944062b7bc2a089d#diff-e2c4a49c4259f8bda03f62e97d5be922R9

We also included this change in our private repo; that is missing as well:  https://git.corp.tc/capsela/consumer-frontend-old/pull/897 (the commit in the new repo: https://github.com/TrueCar/consumer-frontend/commit/856241a50cc3f3cb)

Our particular goal was to use the `before` option to amend the script with `crossOrigin="anonymous"` to get better stack traces in some of our error reporting services, more detail about that below.  For the time being, the `before` hook is the only option we would like to support.

From https://jira.true.sh/browse/SELA-1359:
> On the consumer-frontend side, we noticed generic "Script errors" from both Rollbar and New Relic that lacked useful stack traces. This makes it pretty much impossible to tell what the true error is and how to troubleshoot. There is a community solution article in Rollbar that suggests we open up our CDN response headers (see related DO-644 ticket) and set the `crossorigin="anonymous"` attribute on our <script> tags to retrieve more information: https://rollbar.com/TrueCar/consumer-frontend/items/215/#solutions. This ticket helps out with the script attribute portion of that solution.

**Comment by sethbattin** [comment]
PR incoming

**Comment by zamotany** [comment]
@sethbattin Looks like, I've forgotten about that.
