### ISSUE TITLE
Server side debugging is not working

### ISSUE THREAD

**Issue by chefnobody** [TrueCar/gluestick#975]
# Bug
In a new app, trying to debug the server side code is not working.

## Reproduction steps
```
gluestick new gs-debug
cd gs-debug
echo 'import React from "react";
export default function Home () {
  debugger;
  return <div>Hi</div>;
}  ' > src/apps/main/components/Home.js
gluestick start-server -D
```

## Current Result
The server looks like it should be running and I get a chrome inspector url. However, when I visit http://localhost:8880/ I do not get a breakpoint in the debugger and the console throws this error:
```
[GlueStick][start-server] ERROR:  { errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/aconnolly/workspace/gs-debug/build/assets/webpack-chunks.json' }
```

## Expected Result
Expected inspector to pause on the breakpoint.

**Comment by zamotany** [comment]
This is due to `webpack-chunks.json` not being present which is required for renderer to work properly. You need to run `gluestick build --client` before debugging.
